Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,4 +35,9 @@ jobs:
           git config user.email "$(git log -n 1 --pretty=format:%ae)"
           git add "wau-mods/index.html"
           git commit -m "Updated index.html"
-          git push origin main
+          commit_exit_code=$?  # Capture the exit code
+          if [[ $commit_exit_code -eq 0 ]]; then  # Check if commit was successful
+            git push origin main
+          else  # If commit failed (no changes), print a message
+            echo "No changes detected. Skipping push."
+          fi
